services:
  postgres_app:
    image: postgres:17
    container_name: app_db
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_app_data:/var/lib/postgresql/data
      
  fastapi-app:
    build: ./dh_backend/
    volumes:
      - ./dh_backend/src:/app/src
      - ./data:/data
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - APP_DB_URL=postgresql+asyncpg://admin:password@postgres_app:5432/app_db
    depends_on:
      postgres_app:
        condition: service_started
